TMF620: Product Catalog Management
TMF620E: Product Catalog Management
TMF621: Trouble Ticket Management
TMF621E: Trouble Ticket Management
TMF622: Product Ordering Management
TMF622E: Product Ordering Management
TMF623: SLA Management
TMF628: Performance Management
TMF629: Customer Management
TMF629E: Customer Management
TMF632: Party Management
TMF632E: Party Management
TMF633: Service Catalog Management
TMF634: Resource Catalog Management
TMF635: Usage Management
TMF637: Product Inventory Management
TMF637E: Product Inventory Management
TMF638: Service Inventory Management
TMF638E: Service Inventory Management
TMF639: Resource Inventory Management
TMF640: Service Activation and Configuration
TMF641: Service Ordering Management
TMF642: Alarm Management
TMF644: Privacy Management
TMF645: Service Qualification Management
TMF646: Appointment Management
TMF648: Quote Management
TMF649: Performance Thresholding Management
TMF651: Agreement Management
TMF652: Resource Order Management
TMF653: Service Test Management
TMF654: Prepay Balance Management
TMF655: Change Management
TMF656: Service Problem Management
TMF657: Service Quality Management Management
TMF658: Loyalty Management
TMF662: Entity Catalog Management
TMF663: Shopping Cart Management
TMF664: Resource Function Activation Management
TMF666: Account Management
TMF666E: Account Management
TMF667: Document Management
TMF668: Partnership Management
TMF669: Party Role Management
TMF670: Payment Method Management
TMF671: Promotion Management
TMF672: User Role Permission Management
TMF673: Geographic Address Management
TMF673E: Geographic Address Management
TMF674: Geographic Site Management
TMF675: Geographic Location Management
TMF676: Payment Management
TMF677: Usage Consumption Management
TMF678: Customer Bill Management
TMF678E: Customer Bill Management
TMF679: Product Offering Qualification Management
TMF680: Recommendation Management
TMF681: Communication Management
TMF683: Party Interaction Management
TMF684: Shipment Tracking Management
TMF685: Resource Pool Management
TMF686: Topology Management
TMF687: Stock Management
TMF688: Event Management
TMF691: Federated ID Management
TMF696: Risk Management
TMF697: Work Order Management
TMF699: Sales Management
TMF700: Shipping Order Management
TMF701: Process Flow Management
TMF702: Resource Activation Management
TMF703: Entity Inventory Management
TMF704: Test Case Management
TMF705: Test Environment Management
TMF706: Test Data Management
TMF707: Test Result Management
TMF708: Test Execution Management
TMF709: Test Scenario Management
TMF710: General Test Artifact Management
TMF711: Shipment Management
TMF713: Work Management
TMF714: Work Qualification Management
TMF715: Warranty Management
TMF716: Resource Reservation
TMF717: Customer360 Management
TMF720: Digital Identity Management
TMF723: Policy Management
TMF724: Incident Management
TMF725: Metadata Catalog Management
TMF727: Service Usage Management
TMF728: Dunning Case Management
TMF730: Software And Compute Management
TMF735: CDR Transaction Management
TMF736: Revenue Sharing Algorithm Management
TMF737: Revenue Sharing Report Management
TMF738: Revenue Sharing Model Management
TMF753: Closed Loop Management
TMF759: Private Optimized Binding
TMF760: Product Configuration Management
TMF764: Cost Management
TMF767: Product Usage Management
TMF768: Resource Role Management
TMF769: Product Test
TMF771: Resource Usage Management
TMF777: Outage Management
TMF908: IoT Agent and Device Management
TMF909: Network as a Service Management
TMF910: Self Care Management
TMF914: IoT Service Management
TMF915: AI Management
TMF921: Intent Management
TMF924: DCS 5GSlice Service Activation
TMF931: Open Gateway Onboarding and Ordering Component Suite
TMF936: Open Gateway Product Catalog
