# TMF API 编号到数据域的映射。可根据企业需求扩展或覆盖。
TMF699: MarketingSales
TMF646: Customer
TMF678: Customer
TMF629: Customer
TMF717: Customer
TMF676: Customer
TMF670: Customer
TMF654: Customer
TMF760: Customer
TMF622: Customer
TMF648: Customer
TMF680: Customer
TMF696: Customer
TMF663: Customer
TMF658: Product
TMF936: Product
TMF620: Product
TMF637: Product
TMF679: Product
TMF767: Product
TMF671: Product
TMF677: Product
TMF635: Product
TMF924: Service
TMF914: Service
TMF909: Service
TMF777: Service
TMF640: Service
TMF633: Service
TMF638: Service
TMF641: Service
TMF656: Service
TMF645: Service
TMF657: Service
TMF653: Service
TMF727: Service
TMF642: Resource
TMF908: Resource
TMF759: Resource
TMF702: Resource
TMF634: Resource
TMF664: Resource
TMF639: Resource
TMF652: Resource
TMF685: Resource
TMF716: Resource
TMF768: Resource
TMF771: Resource
TMF730: Resource
TMF687: Resource
TMF666: BusinessPartner
TMF651: BusinessPartner
TMF668: BusinessPartner
TMF683: BusinessPartner
TMF632: BusinessPartner
TMF669: BusinessPartner
TMF644: BusinessPartner
TMF736: BusinessPartner
TMF738: BusinessPartner
TMF737: BusinessPartner
TMF711: BusinessPartner
TMF684: BusinessPartner
TMF700: BusinessPartner
TMF623: BusinessPartner
TMF713: BusinessPartner
TMF915: Common
TMF735: Common
TMF655: Common
TMF681: Common
TMF764: Common
TMF720: Common
TMF667: Common
TMF728: Common
TMF662: Common
TMF703: Common
TMF688: Common
TMF691: Common
TMF710: Common
TMF673: Common
TMF675: Common
TMF674: Common
TMF724: Common
TMF921: Common
TMF725: Common
TMF931: Common
TMF628: Common
TMF649: Common
TMF701: Common
TMF910: Common
TMF704: Common
TMF706: Common
TMF705: Common
TMF708: Common
TMF707: Common
TMF709: Common
TMF686: Common
TMF621: Common
TMF672: Common
TMF715: Common
TMF714: Common
TMF697: BusinessPartner
TMF723: Common
TMF753: Common
TMF769: Product
TMF666E: BusinessPartner
TMF678E: Customer
TMF629E: Customer
TMF673E: Common
TMF632E: BusinessPartner
TMF620E: Product
TMF637E: Product
TMF638E: Service
TMF621E: Common
TMF622E: Customer
